// Code generated by "enumer --text --json --type=GrowCurveType growcurvetype.go"; DO NOT EDIT.

package excel

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _GrowCurveTypeName = "GROW_CURVE_NONEGROW_CURVE_HPGROW_CURVE_ATTACKGROW_CURVE_STAMINAGROW_CURVE_STRIKEGROW_CURVE_ANTI_STRIKEGROW_CURVE_ANTI_STRIKE1GROW_CURVE_ANTI_STRIKE2GROW_CURVE_ANTI_STRIKE3GROW_CURVE_STRIKE_HURTGROW_CURVE_ELEMENTGROW_CURVE_KILL_EXPGROW_CURVE_DEFENSEGROW_CURVE_ATTACK_BOMBGROW_CURVE_HP_LITTLEMONSTERGROW_CURVE_ELEMENT_MASTERYGROW_CURVE_PROGRESSIONGROW_CURVE_DEFENDINGGROW_CURVE_MHPGROW_CURVE_MATKGROW_CURVE_TOWERATKGROW_CURVE_HP_S5GROW_CURVE_HP_S4GROW_CURVE_HP_2GROW_CURVE_ATTACK_2GROW_CURVE_HP_ENVIRONMENTGROW_CURVE_ATTACK_S5GROW_CURVE_ATTACK_S4GROW_CURVE_ATTACK_S3GROW_CURVE_STRIKE_S5GROW_CURVE_DEFENSE_S5GROW_CURVE_DEFENSE_S4GROW_CURVE_ACTIVITY_DEFENSE_2GROW_CURVE_ATTACK_101GROW_CURVE_ATTACK_102GROW_CURVE_ATTACK_103GROW_CURVE_ATTACK_104GROW_CURVE_ATTACK_105GROW_CURVE_ATTACK_201GROW_CURVE_ATTACK_202GROW_CURVE_ATTACK_203GROW_CURVE_ATTACK_204GROW_CURVE_ATTACK_205GROW_CURVE_ATTACK_301GROW_CURVE_ATTACK_302GROW_CURVE_ATTACK_303GROW_CURVE_ATTACK_304GROW_CURVE_ATTACK_305GROW_CURVE_CRITICAL_101GROW_CURVE_CRITICAL_102GROW_CURVE_CRITICAL_103GROW_CURVE_CRITICAL_104GROW_CURVE_CRITICAL_105GROW_CURVE_CRITICAL_201GROW_CURVE_CRITICAL_202GROW_CURVE_CRITICAL_203GROW_CURVE_CRITICAL_204GROW_CURVE_CRITICAL_205GROW_CURVE_CRITICAL_301GROW_CURVE_CRITICAL_302GROW_CURVE_CRITICAL_303GROW_CURVE_CRITICAL_304GROW_CURVE_CRITICAL_305GROW_CURVE_ACTIVITY_ATTACK_1GROW_CURVE_ACTIVITY_HP_1GROW_CURVE_ACTIVITY_ATTACK_2GROW_CURVE_ACTIVITY_HP_2"
const _GrowCurveTypeLowerName = "grow_curve_nonegrow_curve_hpgrow_curve_attackgrow_curve_staminagrow_curve_strikegrow_curve_anti_strikegrow_curve_anti_strike1grow_curve_anti_strike2grow_curve_anti_strike3grow_curve_strike_hurtgrow_curve_elementgrow_curve_kill_expgrow_curve_defensegrow_curve_attack_bombgrow_curve_hp_littlemonstergrow_curve_element_masterygrow_curve_progressiongrow_curve_defendinggrow_curve_mhpgrow_curve_matkgrow_curve_toweratkgrow_curve_hp_s5grow_curve_hp_s4grow_curve_hp_2grow_curve_attack_2grow_curve_hp_environmentgrow_curve_attack_s5grow_curve_attack_s4grow_curve_attack_s3grow_curve_strike_s5grow_curve_defense_s5grow_curve_defense_s4grow_curve_activity_defense_2grow_curve_attack_101grow_curve_attack_102grow_curve_attack_103grow_curve_attack_104grow_curve_attack_105grow_curve_attack_201grow_curve_attack_202grow_curve_attack_203grow_curve_attack_204grow_curve_attack_205grow_curve_attack_301grow_curve_attack_302grow_curve_attack_303grow_curve_attack_304grow_curve_attack_305grow_curve_critical_101grow_curve_critical_102grow_curve_critical_103grow_curve_critical_104grow_curve_critical_105grow_curve_critical_201grow_curve_critical_202grow_curve_critical_203grow_curve_critical_204grow_curve_critical_205grow_curve_critical_301grow_curve_critical_302grow_curve_critical_303grow_curve_critical_304grow_curve_critical_305grow_curve_activity_attack_1grow_curve_activity_hp_1grow_curve_activity_attack_2grow_curve_activity_hp_2"

var _GrowCurveTypeMap = map[GrowCurveType]string{
	0:    _GrowCurveTypeName[0:15],
	1:    _GrowCurveTypeName[15:28],
	2:    _GrowCurveTypeName[28:45],
	3:    _GrowCurveTypeName[45:63],
	4:    _GrowCurveTypeName[63:80],
	5:    _GrowCurveTypeName[80:102],
	6:    _GrowCurveTypeName[102:125],
	7:    _GrowCurveTypeName[125:148],
	8:    _GrowCurveTypeName[148:171],
	9:    _GrowCurveTypeName[171:193],
	10:   _GrowCurveTypeName[193:211],
	11:   _GrowCurveTypeName[211:230],
	12:   _GrowCurveTypeName[230:248],
	13:   _GrowCurveTypeName[248:270],
	14:   _GrowCurveTypeName[270:297],
	15:   _GrowCurveTypeName[297:323],
	16:   _GrowCurveTypeName[323:345],
	17:   _GrowCurveTypeName[345:365],
	18:   _GrowCurveTypeName[365:379],
	19:   _GrowCurveTypeName[379:394],
	20:   _GrowCurveTypeName[394:413],
	21:   _GrowCurveTypeName[413:429],
	22:   _GrowCurveTypeName[429:445],
	23:   _GrowCurveTypeName[445:460],
	24:   _GrowCurveTypeName[460:479],
	25:   _GrowCurveTypeName[479:504],
	31:   _GrowCurveTypeName[504:524],
	32:   _GrowCurveTypeName[524:544],
	33:   _GrowCurveTypeName[544:564],
	34:   _GrowCurveTypeName[564:584],
	41:   _GrowCurveTypeName[584:605],
	42:   _GrowCurveTypeName[605:626],
	570:  _GrowCurveTypeName[626:655],
	1101: _GrowCurveTypeName[655:676],
	1102: _GrowCurveTypeName[676:697],
	1103: _GrowCurveTypeName[697:718],
	1104: _GrowCurveTypeName[718:739],
	1105: _GrowCurveTypeName[739:760],
	1201: _GrowCurveTypeName[760:781],
	1202: _GrowCurveTypeName[781:802],
	1203: _GrowCurveTypeName[802:823],
	1204: _GrowCurveTypeName[823:844],
	1205: _GrowCurveTypeName[844:865],
	1301: _GrowCurveTypeName[865:886],
	1302: _GrowCurveTypeName[886:907],
	1303: _GrowCurveTypeName[907:928],
	1304: _GrowCurveTypeName[928:949],
	1305: _GrowCurveTypeName[949:970],
	2101: _GrowCurveTypeName[970:993],
	2102: _GrowCurveTypeName[993:1016],
	2103: _GrowCurveTypeName[1016:1039],
	2104: _GrowCurveTypeName[1039:1062],
	2105: _GrowCurveTypeName[1062:1085],
	2201: _GrowCurveTypeName[1085:1108],
	2202: _GrowCurveTypeName[1108:1131],
	2203: _GrowCurveTypeName[1131:1154],
	2204: _GrowCurveTypeName[1154:1177],
	2205: _GrowCurveTypeName[1177:1200],
	2301: _GrowCurveTypeName[1200:1223],
	2302: _GrowCurveTypeName[1223:1246],
	2303: _GrowCurveTypeName[1246:1269],
	2304: _GrowCurveTypeName[1269:1292],
	2305: _GrowCurveTypeName[1292:1315],
	5201: _GrowCurveTypeName[1315:1343],
	5202: _GrowCurveTypeName[1343:1367],
	5701: _GrowCurveTypeName[1367:1395],
	5702: _GrowCurveTypeName[1395:1419],
}

func (i GrowCurveType) String() string {
	if str, ok := _GrowCurveTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("GrowCurveType(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GrowCurveTypeNoOp() {
	var x [1]struct{}
	_ = x[GROW_CURVE_NONE-(0)]
	_ = x[GROW_CURVE_HP-(1)]
	_ = x[GROW_CURVE_ATTACK-(2)]
	_ = x[GROW_CURVE_STAMINA-(3)]
	_ = x[GROW_CURVE_STRIKE-(4)]
	_ = x[GROW_CURVE_ANTI_STRIKE-(5)]
	_ = x[GROW_CURVE_ANTI_STRIKE1-(6)]
	_ = x[GROW_CURVE_ANTI_STRIKE2-(7)]
	_ = x[GROW_CURVE_ANTI_STRIKE3-(8)]
	_ = x[GROW_CURVE_STRIKE_HURT-(9)]
	_ = x[GROW_CURVE_ELEMENT-(10)]
	_ = x[GROW_CURVE_KILL_EXP-(11)]
	_ = x[GROW_CURVE_DEFENSE-(12)]
	_ = x[GROW_CURVE_ATTACK_BOMB-(13)]
	_ = x[GROW_CURVE_HP_LITTLEMONSTER-(14)]
	_ = x[GROW_CURVE_ELEMENT_MASTERY-(15)]
	_ = x[GROW_CURVE_PROGRESSION-(16)]
	_ = x[GROW_CURVE_DEFENDING-(17)]
	_ = x[GROW_CURVE_MHP-(18)]
	_ = x[GROW_CURVE_MATK-(19)]
	_ = x[GROW_CURVE_TOWERATK-(20)]
	_ = x[GROW_CURVE_HP_S5-(21)]
	_ = x[GROW_CURVE_HP_S4-(22)]
	_ = x[GROW_CURVE_HP_2-(23)]
	_ = x[GROW_CURVE_ATTACK_2-(24)]
	_ = x[GROW_CURVE_HP_ENVIRONMENT-(25)]
	_ = x[GROW_CURVE_ATTACK_S5-(31)]
	_ = x[GROW_CURVE_ATTACK_S4-(32)]
	_ = x[GROW_CURVE_ATTACK_S3-(33)]
	_ = x[GROW_CURVE_STRIKE_S5-(34)]
	_ = x[GROW_CURVE_DEFENSE_S5-(41)]
	_ = x[GROW_CURVE_DEFENSE_S4-(42)]
	_ = x[GROW_CURVE_ACTIVITY_DEFENSE_2-(570)]
	_ = x[GROW_CURVE_ATTACK_101-(1101)]
	_ = x[GROW_CURVE_ATTACK_102-(1102)]
	_ = x[GROW_CURVE_ATTACK_103-(1103)]
	_ = x[GROW_CURVE_ATTACK_104-(1104)]
	_ = x[GROW_CURVE_ATTACK_105-(1105)]
	_ = x[GROW_CURVE_ATTACK_201-(1201)]
	_ = x[GROW_CURVE_ATTACK_202-(1202)]
	_ = x[GROW_CURVE_ATTACK_203-(1203)]
	_ = x[GROW_CURVE_ATTACK_204-(1204)]
	_ = x[GROW_CURVE_ATTACK_205-(1205)]
	_ = x[GROW_CURVE_ATTACK_301-(1301)]
	_ = x[GROW_CURVE_ATTACK_302-(1302)]
	_ = x[GROW_CURVE_ATTACK_303-(1303)]
	_ = x[GROW_CURVE_ATTACK_304-(1304)]
	_ = x[GROW_CURVE_ATTACK_305-(1305)]
	_ = x[GROW_CURVE_CRITICAL_101-(2101)]
	_ = x[GROW_CURVE_CRITICAL_102-(2102)]
	_ = x[GROW_CURVE_CRITICAL_103-(2103)]
	_ = x[GROW_CURVE_CRITICAL_104-(2104)]
	_ = x[GROW_CURVE_CRITICAL_105-(2105)]
	_ = x[GROW_CURVE_CRITICAL_201-(2201)]
	_ = x[GROW_CURVE_CRITICAL_202-(2202)]
	_ = x[GROW_CURVE_CRITICAL_203-(2203)]
	_ = x[GROW_CURVE_CRITICAL_204-(2204)]
	_ = x[GROW_CURVE_CRITICAL_205-(2205)]
	_ = x[GROW_CURVE_CRITICAL_301-(2301)]
	_ = x[GROW_CURVE_CRITICAL_302-(2302)]
	_ = x[GROW_CURVE_CRITICAL_303-(2303)]
	_ = x[GROW_CURVE_CRITICAL_304-(2304)]
	_ = x[GROW_CURVE_CRITICAL_305-(2305)]
	_ = x[GROW_CURVE_ACTIVITY_ATTACK_1-(5201)]
	_ = x[GROW_CURVE_ACTIVITY_HP_1-(5202)]
	_ = x[GROW_CURVE_ACTIVITY_ATTACK_2-(5701)]
	_ = x[GROW_CURVE_ACTIVITY_HP_2-(5702)]
}

var _GrowCurveTypeValues = []GrowCurveType{GROW_CURVE_NONE, GROW_CURVE_HP, GROW_CURVE_ATTACK, GROW_CURVE_STAMINA, GROW_CURVE_STRIKE, GROW_CURVE_ANTI_STRIKE, GROW_CURVE_ANTI_STRIKE1, GROW_CURVE_ANTI_STRIKE2, GROW_CURVE_ANTI_STRIKE3, GROW_CURVE_STRIKE_HURT, GROW_CURVE_ELEMENT, GROW_CURVE_KILL_EXP, GROW_CURVE_DEFENSE, GROW_CURVE_ATTACK_BOMB, GROW_CURVE_HP_LITTLEMONSTER, GROW_CURVE_ELEMENT_MASTERY, GROW_CURVE_PROGRESSION, GROW_CURVE_DEFENDING, GROW_CURVE_MHP, GROW_CURVE_MATK, GROW_CURVE_TOWERATK, GROW_CURVE_HP_S5, GROW_CURVE_HP_S4, GROW_CURVE_HP_2, GROW_CURVE_ATTACK_2, GROW_CURVE_HP_ENVIRONMENT, GROW_CURVE_ATTACK_S5, GROW_CURVE_ATTACK_S4, GROW_CURVE_ATTACK_S3, GROW_CURVE_STRIKE_S5, GROW_CURVE_DEFENSE_S5, GROW_CURVE_DEFENSE_S4, GROW_CURVE_ACTIVITY_DEFENSE_2, GROW_CURVE_ATTACK_101, GROW_CURVE_ATTACK_102, GROW_CURVE_ATTACK_103, GROW_CURVE_ATTACK_104, GROW_CURVE_ATTACK_105, GROW_CURVE_ATTACK_201, GROW_CURVE_ATTACK_202, GROW_CURVE_ATTACK_203, GROW_CURVE_ATTACK_204, GROW_CURVE_ATTACK_205, GROW_CURVE_ATTACK_301, GROW_CURVE_ATTACK_302, GROW_CURVE_ATTACK_303, GROW_CURVE_ATTACK_304, GROW_CURVE_ATTACK_305, GROW_CURVE_CRITICAL_101, GROW_CURVE_CRITICAL_102, GROW_CURVE_CRITICAL_103, GROW_CURVE_CRITICAL_104, GROW_CURVE_CRITICAL_105, GROW_CURVE_CRITICAL_201, GROW_CURVE_CRITICAL_202, GROW_CURVE_CRITICAL_203, GROW_CURVE_CRITICAL_204, GROW_CURVE_CRITICAL_205, GROW_CURVE_CRITICAL_301, GROW_CURVE_CRITICAL_302, GROW_CURVE_CRITICAL_303, GROW_CURVE_CRITICAL_304, GROW_CURVE_CRITICAL_305, GROW_CURVE_ACTIVITY_ATTACK_1, GROW_CURVE_ACTIVITY_HP_1, GROW_CURVE_ACTIVITY_ATTACK_2, GROW_CURVE_ACTIVITY_HP_2}

var _GrowCurveTypeNameToValueMap = map[string]GrowCurveType{
	_GrowCurveTypeName[0:15]:           GROW_CURVE_NONE,
	_GrowCurveTypeLowerName[0:15]:      GROW_CURVE_NONE,
	_GrowCurveTypeName[15:28]:          GROW_CURVE_HP,
	_GrowCurveTypeLowerName[15:28]:     GROW_CURVE_HP,
	_GrowCurveTypeName[28:45]:          GROW_CURVE_ATTACK,
	_GrowCurveTypeLowerName[28:45]:     GROW_CURVE_ATTACK,
	_GrowCurveTypeName[45:63]:          GROW_CURVE_STAMINA,
	_GrowCurveTypeLowerName[45:63]:     GROW_CURVE_STAMINA,
	_GrowCurveTypeName[63:80]:          GROW_CURVE_STRIKE,
	_GrowCurveTypeLowerName[63:80]:     GROW_CURVE_STRIKE,
	_GrowCurveTypeName[80:102]:         GROW_CURVE_ANTI_STRIKE,
	_GrowCurveTypeLowerName[80:102]:    GROW_CURVE_ANTI_STRIKE,
	_GrowCurveTypeName[102:125]:        GROW_CURVE_ANTI_STRIKE1,
	_GrowCurveTypeLowerName[102:125]:   GROW_CURVE_ANTI_STRIKE1,
	_GrowCurveTypeName[125:148]:        GROW_CURVE_ANTI_STRIKE2,
	_GrowCurveTypeLowerName[125:148]:   GROW_CURVE_ANTI_STRIKE2,
	_GrowCurveTypeName[148:171]:        GROW_CURVE_ANTI_STRIKE3,
	_GrowCurveTypeLowerName[148:171]:   GROW_CURVE_ANTI_STRIKE3,
	_GrowCurveTypeName[171:193]:        GROW_CURVE_STRIKE_HURT,
	_GrowCurveTypeLowerName[171:193]:   GROW_CURVE_STRIKE_HURT,
	_GrowCurveTypeName[193:211]:        GROW_CURVE_ELEMENT,
	_GrowCurveTypeLowerName[193:211]:   GROW_CURVE_ELEMENT,
	_GrowCurveTypeName[211:230]:        GROW_CURVE_KILL_EXP,
	_GrowCurveTypeLowerName[211:230]:   GROW_CURVE_KILL_EXP,
	_GrowCurveTypeName[230:248]:        GROW_CURVE_DEFENSE,
	_GrowCurveTypeLowerName[230:248]:   GROW_CURVE_DEFENSE,
	_GrowCurveTypeName[248:270]:        GROW_CURVE_ATTACK_BOMB,
	_GrowCurveTypeLowerName[248:270]:   GROW_CURVE_ATTACK_BOMB,
	_GrowCurveTypeName[270:297]:        GROW_CURVE_HP_LITTLEMONSTER,
	_GrowCurveTypeLowerName[270:297]:   GROW_CURVE_HP_LITTLEMONSTER,
	_GrowCurveTypeName[297:323]:        GROW_CURVE_ELEMENT_MASTERY,
	_GrowCurveTypeLowerName[297:323]:   GROW_CURVE_ELEMENT_MASTERY,
	_GrowCurveTypeName[323:345]:        GROW_CURVE_PROGRESSION,
	_GrowCurveTypeLowerName[323:345]:   GROW_CURVE_PROGRESSION,
	_GrowCurveTypeName[345:365]:        GROW_CURVE_DEFENDING,
	_GrowCurveTypeLowerName[345:365]:   GROW_CURVE_DEFENDING,
	_GrowCurveTypeName[365:379]:        GROW_CURVE_MHP,
	_GrowCurveTypeLowerName[365:379]:   GROW_CURVE_MHP,
	_GrowCurveTypeName[379:394]:        GROW_CURVE_MATK,
	_GrowCurveTypeLowerName[379:394]:   GROW_CURVE_MATK,
	_GrowCurveTypeName[394:413]:        GROW_CURVE_TOWERATK,
	_GrowCurveTypeLowerName[394:413]:   GROW_CURVE_TOWERATK,
	_GrowCurveTypeName[413:429]:        GROW_CURVE_HP_S5,
	_GrowCurveTypeLowerName[413:429]:   GROW_CURVE_HP_S5,
	_GrowCurveTypeName[429:445]:        GROW_CURVE_HP_S4,
	_GrowCurveTypeLowerName[429:445]:   GROW_CURVE_HP_S4,
	_GrowCurveTypeName[445:460]:        GROW_CURVE_HP_2,
	_GrowCurveTypeLowerName[445:460]:   GROW_CURVE_HP_2,
	_GrowCurveTypeName[460:479]:        GROW_CURVE_ATTACK_2,
	_GrowCurveTypeLowerName[460:479]:   GROW_CURVE_ATTACK_2,
	_GrowCurveTypeName[479:504]:        GROW_CURVE_HP_ENVIRONMENT,
	_GrowCurveTypeLowerName[479:504]:   GROW_CURVE_HP_ENVIRONMENT,
	_GrowCurveTypeName[504:524]:        GROW_CURVE_ATTACK_S5,
	_GrowCurveTypeLowerName[504:524]:   GROW_CURVE_ATTACK_S5,
	_GrowCurveTypeName[524:544]:        GROW_CURVE_ATTACK_S4,
	_GrowCurveTypeLowerName[524:544]:   GROW_CURVE_ATTACK_S4,
	_GrowCurveTypeName[544:564]:        GROW_CURVE_ATTACK_S3,
	_GrowCurveTypeLowerName[544:564]:   GROW_CURVE_ATTACK_S3,
	_GrowCurveTypeName[564:584]:        GROW_CURVE_STRIKE_S5,
	_GrowCurveTypeLowerName[564:584]:   GROW_CURVE_STRIKE_S5,
	_GrowCurveTypeName[584:605]:        GROW_CURVE_DEFENSE_S5,
	_GrowCurveTypeLowerName[584:605]:   GROW_CURVE_DEFENSE_S5,
	_GrowCurveTypeName[605:626]:        GROW_CURVE_DEFENSE_S4,
	_GrowCurveTypeLowerName[605:626]:   GROW_CURVE_DEFENSE_S4,
	_GrowCurveTypeName[626:655]:        GROW_CURVE_ACTIVITY_DEFENSE_2,
	_GrowCurveTypeLowerName[626:655]:   GROW_CURVE_ACTIVITY_DEFENSE_2,
	_GrowCurveTypeName[655:676]:        GROW_CURVE_ATTACK_101,
	_GrowCurveTypeLowerName[655:676]:   GROW_CURVE_ATTACK_101,
	_GrowCurveTypeName[676:697]:        GROW_CURVE_ATTACK_102,
	_GrowCurveTypeLowerName[676:697]:   GROW_CURVE_ATTACK_102,
	_GrowCurveTypeName[697:718]:        GROW_CURVE_ATTACK_103,
	_GrowCurveTypeLowerName[697:718]:   GROW_CURVE_ATTACK_103,
	_GrowCurveTypeName[718:739]:        GROW_CURVE_ATTACK_104,
	_GrowCurveTypeLowerName[718:739]:   GROW_CURVE_ATTACK_104,
	_GrowCurveTypeName[739:760]:        GROW_CURVE_ATTACK_105,
	_GrowCurveTypeLowerName[739:760]:   GROW_CURVE_ATTACK_105,
	_GrowCurveTypeName[760:781]:        GROW_CURVE_ATTACK_201,
	_GrowCurveTypeLowerName[760:781]:   GROW_CURVE_ATTACK_201,
	_GrowCurveTypeName[781:802]:        GROW_CURVE_ATTACK_202,
	_GrowCurveTypeLowerName[781:802]:   GROW_CURVE_ATTACK_202,
	_GrowCurveTypeName[802:823]:        GROW_CURVE_ATTACK_203,
	_GrowCurveTypeLowerName[802:823]:   GROW_CURVE_ATTACK_203,
	_GrowCurveTypeName[823:844]:        GROW_CURVE_ATTACK_204,
	_GrowCurveTypeLowerName[823:844]:   GROW_CURVE_ATTACK_204,
	_GrowCurveTypeName[844:865]:        GROW_CURVE_ATTACK_205,
	_GrowCurveTypeLowerName[844:865]:   GROW_CURVE_ATTACK_205,
	_GrowCurveTypeName[865:886]:        GROW_CURVE_ATTACK_301,
	_GrowCurveTypeLowerName[865:886]:   GROW_CURVE_ATTACK_301,
	_GrowCurveTypeName[886:907]:        GROW_CURVE_ATTACK_302,
	_GrowCurveTypeLowerName[886:907]:   GROW_CURVE_ATTACK_302,
	_GrowCurveTypeName[907:928]:        GROW_CURVE_ATTACK_303,
	_GrowCurveTypeLowerName[907:928]:   GROW_CURVE_ATTACK_303,
	_GrowCurveTypeName[928:949]:        GROW_CURVE_ATTACK_304,
	_GrowCurveTypeLowerName[928:949]:   GROW_CURVE_ATTACK_304,
	_GrowCurveTypeName[949:970]:        GROW_CURVE_ATTACK_305,
	_GrowCurveTypeLowerName[949:970]:   GROW_CURVE_ATTACK_305,
	_GrowCurveTypeName[970:993]:        GROW_CURVE_CRITICAL_101,
	_GrowCurveTypeLowerName[970:993]:   GROW_CURVE_CRITICAL_101,
	_GrowCurveTypeName[993:1016]:       GROW_CURVE_CRITICAL_102,
	_GrowCurveTypeLowerName[993:1016]:  GROW_CURVE_CRITICAL_102,
	_GrowCurveTypeName[1016:1039]:      GROW_CURVE_CRITICAL_103,
	_GrowCurveTypeLowerName[1016:1039]: GROW_CURVE_CRITICAL_103,
	_GrowCurveTypeName[1039:1062]:      GROW_CURVE_CRITICAL_104,
	_GrowCurveTypeLowerName[1039:1062]: GROW_CURVE_CRITICAL_104,
	_GrowCurveTypeName[1062:1085]:      GROW_CURVE_CRITICAL_105,
	_GrowCurveTypeLowerName[1062:1085]: GROW_CURVE_CRITICAL_105,
	_GrowCurveTypeName[1085:1108]:      GROW_CURVE_CRITICAL_201,
	_GrowCurveTypeLowerName[1085:1108]: GROW_CURVE_CRITICAL_201,
	_GrowCurveTypeName[1108:1131]:      GROW_CURVE_CRITICAL_202,
	_GrowCurveTypeLowerName[1108:1131]: GROW_CURVE_CRITICAL_202,
	_GrowCurveTypeName[1131:1154]:      GROW_CURVE_CRITICAL_203,
	_GrowCurveTypeLowerName[1131:1154]: GROW_CURVE_CRITICAL_203,
	_GrowCurveTypeName[1154:1177]:      GROW_CURVE_CRITICAL_204,
	_GrowCurveTypeLowerName[1154:1177]: GROW_CURVE_CRITICAL_204,
	_GrowCurveTypeName[1177:1200]:      GROW_CURVE_CRITICAL_205,
	_GrowCurveTypeLowerName[1177:1200]: GROW_CURVE_CRITICAL_205,
	_GrowCurveTypeName[1200:1223]:      GROW_CURVE_CRITICAL_301,
	_GrowCurveTypeLowerName[1200:1223]: GROW_CURVE_CRITICAL_301,
	_GrowCurveTypeName[1223:1246]:      GROW_CURVE_CRITICAL_302,
	_GrowCurveTypeLowerName[1223:1246]: GROW_CURVE_CRITICAL_302,
	_GrowCurveTypeName[1246:1269]:      GROW_CURVE_CRITICAL_303,
	_GrowCurveTypeLowerName[1246:1269]: GROW_CURVE_CRITICAL_303,
	_GrowCurveTypeName[1269:1292]:      GROW_CURVE_CRITICAL_304,
	_GrowCurveTypeLowerName[1269:1292]: GROW_CURVE_CRITICAL_304,
	_GrowCurveTypeName[1292:1315]:      GROW_CURVE_CRITICAL_305,
	_GrowCurveTypeLowerName[1292:1315]: GROW_CURVE_CRITICAL_305,
	_GrowCurveTypeName[1315:1343]:      GROW_CURVE_ACTIVITY_ATTACK_1,
	_GrowCurveTypeLowerName[1315:1343]: GROW_CURVE_ACTIVITY_ATTACK_1,
	_GrowCurveTypeName[1343:1367]:      GROW_CURVE_ACTIVITY_HP_1,
	_GrowCurveTypeLowerName[1343:1367]: GROW_CURVE_ACTIVITY_HP_1,
	_GrowCurveTypeName[1367:1395]:      GROW_CURVE_ACTIVITY_ATTACK_2,
	_GrowCurveTypeLowerName[1367:1395]: GROW_CURVE_ACTIVITY_ATTACK_2,
	_GrowCurveTypeName[1395:1419]:      GROW_CURVE_ACTIVITY_HP_2,
	_GrowCurveTypeLowerName[1395:1419]: GROW_CURVE_ACTIVITY_HP_2,
}

var _GrowCurveTypeNames = []string{
	_GrowCurveTypeName[0:15],
	_GrowCurveTypeName[15:28],
	_GrowCurveTypeName[28:45],
	_GrowCurveTypeName[45:63],
	_GrowCurveTypeName[63:80],
	_GrowCurveTypeName[80:102],
	_GrowCurveTypeName[102:125],
	_GrowCurveTypeName[125:148],
	_GrowCurveTypeName[148:171],
	_GrowCurveTypeName[171:193],
	_GrowCurveTypeName[193:211],
	_GrowCurveTypeName[211:230],
	_GrowCurveTypeName[230:248],
	_GrowCurveTypeName[248:270],
	_GrowCurveTypeName[270:297],
	_GrowCurveTypeName[297:323],
	_GrowCurveTypeName[323:345],
	_GrowCurveTypeName[345:365],
	_GrowCurveTypeName[365:379],
	_GrowCurveTypeName[379:394],
	_GrowCurveTypeName[394:413],
	_GrowCurveTypeName[413:429],
	_GrowCurveTypeName[429:445],
	_GrowCurveTypeName[445:460],
	_GrowCurveTypeName[460:479],
	_GrowCurveTypeName[479:504],
	_GrowCurveTypeName[504:524],
	_GrowCurveTypeName[524:544],
	_GrowCurveTypeName[544:564],
	_GrowCurveTypeName[564:584],
	_GrowCurveTypeName[584:605],
	_GrowCurveTypeName[605:626],
	_GrowCurveTypeName[626:655],
	_GrowCurveTypeName[655:676],
	_GrowCurveTypeName[676:697],
	_GrowCurveTypeName[697:718],
	_GrowCurveTypeName[718:739],
	_GrowCurveTypeName[739:760],
	_GrowCurveTypeName[760:781],
	_GrowCurveTypeName[781:802],
	_GrowCurveTypeName[802:823],
	_GrowCurveTypeName[823:844],
	_GrowCurveTypeName[844:865],
	_GrowCurveTypeName[865:886],
	_GrowCurveTypeName[886:907],
	_GrowCurveTypeName[907:928],
	_GrowCurveTypeName[928:949],
	_GrowCurveTypeName[949:970],
	_GrowCurveTypeName[970:993],
	_GrowCurveTypeName[993:1016],
	_GrowCurveTypeName[1016:1039],
	_GrowCurveTypeName[1039:1062],
	_GrowCurveTypeName[1062:1085],
	_GrowCurveTypeName[1085:1108],
	_GrowCurveTypeName[1108:1131],
	_GrowCurveTypeName[1131:1154],
	_GrowCurveTypeName[1154:1177],
	_GrowCurveTypeName[1177:1200],
	_GrowCurveTypeName[1200:1223],
	_GrowCurveTypeName[1223:1246],
	_GrowCurveTypeName[1246:1269],
	_GrowCurveTypeName[1269:1292],
	_GrowCurveTypeName[1292:1315],
	_GrowCurveTypeName[1315:1343],
	_GrowCurveTypeName[1343:1367],
	_GrowCurveTypeName[1367:1395],
	_GrowCurveTypeName[1395:1419],
}

// GrowCurveTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GrowCurveTypeString(s string) (GrowCurveType, error) {
	if val, ok := _GrowCurveTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GrowCurveTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GrowCurveType values", s)
}

// GrowCurveTypeValues returns all values of the enum
func GrowCurveTypeValues() []GrowCurveType {
	return _GrowCurveTypeValues
}

// GrowCurveTypeStrings returns a slice of all String values of the enum
func GrowCurveTypeStrings() []string {
	strs := make([]string, len(_GrowCurveTypeNames))
	copy(strs, _GrowCurveTypeNames)
	return strs
}

// IsAGrowCurveType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GrowCurveType) IsAGrowCurveType() bool {
	_, ok := _GrowCurveTypeMap[i]
	return ok
}

// MarshalJSON implements the json.Marshaler interface for GrowCurveType
func (i GrowCurveType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GrowCurveType
func (i *GrowCurveType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GrowCurveType should be a string, got %s", data)
	}

	var err error
	*i, err = GrowCurveTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for GrowCurveType
func (i GrowCurveType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for GrowCurveType
func (i *GrowCurveType) UnmarshalText(text []byte) error {
	var err error
	*i, err = GrowCurveTypeString(string(text))
	return err
}
