// Code generated by "enumer --text --json --type=ItemType itemtype.go"; DO NOT EDIT.

package excel

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ItemTypeName = "ITEM_NONEITEM_VIRTUALITEM_MATERIALITEM_RELIQUARYITEM_WEAPONITEM_DISPLAYITEM_FURNITURE"

var _ItemTypeIndex = [...]uint8{0, 9, 21, 34, 48, 59, 71, 85}

const _ItemTypeLowerName = "item_noneitem_virtualitem_materialitem_reliquaryitem_weaponitem_displayitem_furniture"

func (i ItemType) String() string {
	if i >= ItemType(len(_ItemTypeIndex)-1) {
		return fmt.Sprintf("ItemType(%d)", i)
	}
	return _ItemTypeName[_ItemTypeIndex[i]:_ItemTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ItemTypeNoOp() {
	var x [1]struct{}
	_ = x[ITEM_NONE-(0)]
	_ = x[ITEM_VIRTUAL-(1)]
	_ = x[ITEM_MATERIAL-(2)]
	_ = x[ITEM_RELIQUARY-(3)]
	_ = x[ITEM_WEAPON-(4)]
	_ = x[ITEM_DISPLAY-(5)]
	_ = x[ITEM_FURNITURE-(6)]
}

var _ItemTypeValues = []ItemType{ITEM_NONE, ITEM_VIRTUAL, ITEM_MATERIAL, ITEM_RELIQUARY, ITEM_WEAPON, ITEM_DISPLAY, ITEM_FURNITURE}

var _ItemTypeNameToValueMap = map[string]ItemType{
	_ItemTypeName[0:9]:        ITEM_NONE,
	_ItemTypeLowerName[0:9]:   ITEM_NONE,
	_ItemTypeName[9:21]:       ITEM_VIRTUAL,
	_ItemTypeLowerName[9:21]:  ITEM_VIRTUAL,
	_ItemTypeName[21:34]:      ITEM_MATERIAL,
	_ItemTypeLowerName[21:34]: ITEM_MATERIAL,
	_ItemTypeName[34:48]:      ITEM_RELIQUARY,
	_ItemTypeLowerName[34:48]: ITEM_RELIQUARY,
	_ItemTypeName[48:59]:      ITEM_WEAPON,
	_ItemTypeLowerName[48:59]: ITEM_WEAPON,
	_ItemTypeName[59:71]:      ITEM_DISPLAY,
	_ItemTypeLowerName[59:71]: ITEM_DISPLAY,
	_ItemTypeName[71:85]:      ITEM_FURNITURE,
	_ItemTypeLowerName[71:85]: ITEM_FURNITURE,
}

var _ItemTypeNames = []string{
	_ItemTypeName[0:9],
	_ItemTypeName[9:21],
	_ItemTypeName[21:34],
	_ItemTypeName[34:48],
	_ItemTypeName[48:59],
	_ItemTypeName[59:71],
	_ItemTypeName[71:85],
}

// ItemTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ItemTypeString(s string) (ItemType, error) {
	if val, ok := _ItemTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ItemTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ItemType values", s)
}

// ItemTypeValues returns all values of the enum
func ItemTypeValues() []ItemType {
	return _ItemTypeValues
}

// ItemTypeStrings returns a slice of all String values of the enum
func ItemTypeStrings() []string {
	strs := make([]string, len(_ItemTypeNames))
	copy(strs, _ItemTypeNames)
	return strs
}

// IsAItemType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ItemType) IsAItemType() bool {
	for _, v := range _ItemTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ItemType
func (i ItemType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ItemType
func (i *ItemType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ItemType should be a string, got %s", data)
	}

	var err error
	*i, err = ItemTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ItemType
func (i ItemType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ItemType
func (i *ItemType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ItemTypeString(string(text))
	return err
}
