// Code generated by "enumer --text --json --type=PlayerProp playerprop.go"; DO NOT EDIT.

package excel

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_PlayerPropName_0      = "PROP_NONE"
	_PlayerPropLowerName_0 = "prop_none"
	_PlayerPropName_1      = "PROP_EXPPROP_BREAK_LEVELPROP_SATIATION_VALPROP_SATIATION_PENALTY_TIME"
	_PlayerPropLowerName_1 = "prop_expprop_break_levelprop_satiation_valprop_satiation_penalty_time"
	_PlayerPropName_2      = "PROP_GEAR_START_VALPROP_GEAR_STOP_VAL"
	_PlayerPropLowerName_2 = "prop_gear_start_valprop_gear_stop_val"
	_PlayerPropName_3      = "PROP_LEVEL"
	_PlayerPropLowerName_3 = "prop_level"
	_PlayerPropName_4      = "PROP_LAST_CHANGE_AVATAR_TIMEPROP_MAX_SPRING_VOLUMEPROP_CUR_SPRING_VOLUMEPROP_IS_SPRING_AUTO_USEPROP_SPRING_AUTO_USE_PERCENTPROP_IS_FLYABLEPROP_IS_WEATHER_LOCKEDPROP_IS_GAME_TIME_LOCKEDPROP_IS_TRANSFERABLEPROP_MAX_STAMINAPROP_CUR_PERSIST_STAMINAPROP_CUR_TEMPORARY_STAMINAPROP_PLAYER_LEVELPROP_PLAYER_EXPPROP_PLAYER_HCOINPROP_PLAYER_SCOINPROP_PLAYER_MP_SETTING_TYPEPROP_IS_MP_MODE_AVAILABLEPROP_PLAYER_WORLD_LEVELPROP_PLAYER_RESIN"
	_PlayerPropLowerName_4 = "prop_last_change_avatar_timeprop_max_spring_volumeprop_cur_spring_volumeprop_is_spring_auto_useprop_spring_auto_use_percentprop_is_flyableprop_is_weather_lockedprop_is_game_time_lockedprop_is_transferableprop_max_staminaprop_cur_persist_staminaprop_cur_temporary_staminaprop_player_levelprop_player_expprop_player_hcoinprop_player_scoinprop_player_mp_setting_typeprop_is_mp_mode_availableprop_player_world_levelprop_player_resin"
	_PlayerPropName_5      = "PROP_PLAYER_WAIT_SUB_HCOINPROP_PLAYER_WAIT_SUB_SCOINPROP_IS_ONLY_MP_WITH_PS_PLAYERPROP_PLAYER_MCOINPROP_PLAYER_WAIT_SUB_MCOINPROP_PLAYER_LEGENDARY_KEYPROP_IS_HAS_FIRST_SHAREPROP_PLAYER_FORGE_POINT"
	_PlayerPropLowerName_5 = "prop_player_wait_sub_hcoinprop_player_wait_sub_scoinprop_is_only_mp_with_ps_playerprop_player_mcoinprop_player_wait_sub_mcoinprop_player_legendary_keyprop_is_has_first_shareprop_player_forge_point"
	_PlayerPropName_6      = "PROP_CUR_CLIMATE_METERPROP_CUR_CLIMATE_TYPEPROP_CUR_CLIMATE_AREA_IDPROP_CUR_CLIMATE_AREA_CLIMATE_TYPEPROP_PLAYER_WORLD_LEVEL_LIMITPROP_PLAYER_WORLD_LEVEL_ADJUST_CDPROP_PLAYER_LEGENDARY_DAILY_TASK_NUMPROP_PLAYER_HOME_COINPROP_PLAYER_WAIT_SUB_HOME_COINPROP_IS_AUTO_UNLOCK_SPECIFIC_EQUIPPROP_PLAYER_GCG_COINPROP_PLAYER_WAIT_SUB_GCG_COINPROP_PLAYER_ONLINE_TIMEPROP_IS_DIVEABLEPROP_MAX_DIVE_STAMINAPROP_CUR_PERSIST_DIVE_STAMINAPROP_IS_CAN_PUT_FIVE_STAR_RELIQUARYPROP_IS_AUTO_LOCK_FIVE_STAR_RELIQUARYPROP_PLAYER_ROLE_COMBAT_COINPROP_CUR_PHLOGISTONPROP_RELIQUARY_TEMPORARY_EXPPROP_IS_MP_CROSS_PLATFORM_ENABLEDPROP_IS_ONLY_MP_WITH_PLATFORM_PLAYERPROP_PLAYER_MUSIC_GAME_BOOK_COINPROP_IS_NOT_SHOW_RELIQUARY_RECOMMAND_PROP"
	_PlayerPropLowerName_6 = "prop_cur_climate_meterprop_cur_climate_typeprop_cur_climate_area_idprop_cur_climate_area_climate_typeprop_player_world_level_limitprop_player_world_level_adjust_cdprop_player_legendary_daily_task_numprop_player_home_coinprop_player_wait_sub_home_coinprop_is_auto_unlock_specific_equipprop_player_gcg_coinprop_player_wait_sub_gcg_coinprop_player_online_timeprop_is_diveableprop_max_dive_staminaprop_cur_persist_dive_staminaprop_is_can_put_five_star_reliquaryprop_is_auto_lock_five_star_reliquaryprop_player_role_combat_coinprop_cur_phlogistonprop_reliquary_temporary_expprop_is_mp_cross_platform_enabledprop_is_only_mp_with_platform_playerprop_player_music_game_book_coinprop_is_not_show_reliquary_recommand_prop"
	_PlayerPropName_7      = "PROP_SHOW_RELIQUARY_RECOMMAND_PROP_STATUS"
	_PlayerPropLowerName_7 = "prop_show_reliquary_recommand_prop_status"
)

var (
	_PlayerPropIndex_0 = [...]uint8{0, 9}
	_PlayerPropIndex_1 = [...]uint8{0, 8, 24, 42, 69}
	_PlayerPropIndex_2 = [...]uint8{0, 19, 37}
	_PlayerPropIndex_3 = [...]uint8{0, 10}
	_PlayerPropIndex_4 = [...]uint16{0, 28, 50, 72, 95, 123, 138, 160, 184, 204, 220, 244, 270, 287, 302, 319, 336, 363, 388, 411, 428}
	_PlayerPropIndex_5 = [...]uint8{0, 26, 52, 82, 99, 125, 150, 173, 196}
	_PlayerPropIndex_6 = [...]uint16{0, 22, 43, 67, 101, 130, 163, 199, 220, 250, 284, 304, 333, 356, 372, 393, 422, 457, 494, 522, 541, 569, 602, 638, 670, 711}
	_PlayerPropIndex_7 = [...]uint8{0, 41}
)

func (i PlayerProp) String() string {
	switch {
	case i == 0:
		return _PlayerPropName_0
	case 1001 <= i && i <= 1004:
		i -= 1001
		return _PlayerPropName_1[_PlayerPropIndex_1[i]:_PlayerPropIndex_1[i+1]]
	case 2001 <= i && i <= 2002:
		i -= 2001
		return _PlayerPropName_2[_PlayerPropIndex_2[i]:_PlayerPropIndex_2[i+1]]
	case i == 4001:
		return _PlayerPropName_3
	case 10001 <= i && i <= 10020:
		i -= 10001
		return _PlayerPropName_4[_PlayerPropIndex_4[i]:_PlayerPropIndex_4[i+1]]
	case 10022 <= i && i <= 10029:
		i -= 10022
		return _PlayerPropName_5[_PlayerPropIndex_5[i]:_PlayerPropIndex_5[i+1]]
	case 10035 <= i && i <= 10059:
		i -= 10035
		return _PlayerPropName_6[_PlayerPropIndex_6[i]:_PlayerPropIndex_6[i+1]]
	case i == 10100:
		return _PlayerPropName_7
	default:
		return fmt.Sprintf("PlayerProp(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PlayerPropNoOp() {
	var x [1]struct{}
	_ = x[PROP_NONE-(0)]
	_ = x[PROP_EXP-(1001)]
	_ = x[PROP_BREAK_LEVEL-(1002)]
	_ = x[PROP_SATIATION_VAL-(1003)]
	_ = x[PROP_SATIATION_PENALTY_TIME-(1004)]
	_ = x[PROP_GEAR_START_VAL-(2001)]
	_ = x[PROP_GEAR_STOP_VAL-(2002)]
	_ = x[PROP_LEVEL-(4001)]
	_ = x[PROP_LAST_CHANGE_AVATAR_TIME-(10001)]
	_ = x[PROP_MAX_SPRING_VOLUME-(10002)]
	_ = x[PROP_CUR_SPRING_VOLUME-(10003)]
	_ = x[PROP_IS_SPRING_AUTO_USE-(10004)]
	_ = x[PROP_SPRING_AUTO_USE_PERCENT-(10005)]
	_ = x[PROP_IS_FLYABLE-(10006)]
	_ = x[PROP_IS_WEATHER_LOCKED-(10007)]
	_ = x[PROP_IS_GAME_TIME_LOCKED-(10008)]
	_ = x[PROP_IS_TRANSFERABLE-(10009)]
	_ = x[PROP_MAX_STAMINA-(10010)]
	_ = x[PROP_CUR_PERSIST_STAMINA-(10011)]
	_ = x[PROP_CUR_TEMPORARY_STAMINA-(10012)]
	_ = x[PROP_PLAYER_LEVEL-(10013)]
	_ = x[PROP_PLAYER_EXP-(10014)]
	_ = x[PROP_PLAYER_HCOIN-(10015)]
	_ = x[PROP_PLAYER_SCOIN-(10016)]
	_ = x[PROP_PLAYER_MP_SETTING_TYPE-(10017)]
	_ = x[PROP_IS_MP_MODE_AVAILABLE-(10018)]
	_ = x[PROP_PLAYER_WORLD_LEVEL-(10019)]
	_ = x[PROP_PLAYER_RESIN-(10020)]
	_ = x[PROP_PLAYER_WAIT_SUB_HCOIN-(10022)]
	_ = x[PROP_PLAYER_WAIT_SUB_SCOIN-(10023)]
	_ = x[PROP_IS_ONLY_MP_WITH_PS_PLAYER-(10024)]
	_ = x[PROP_PLAYER_MCOIN-(10025)]
	_ = x[PROP_PLAYER_WAIT_SUB_MCOIN-(10026)]
	_ = x[PROP_PLAYER_LEGENDARY_KEY-(10027)]
	_ = x[PROP_IS_HAS_FIRST_SHARE-(10028)]
	_ = x[PROP_PLAYER_FORGE_POINT-(10029)]
	_ = x[PROP_CUR_CLIMATE_METER-(10035)]
	_ = x[PROP_CUR_CLIMATE_TYPE-(10036)]
	_ = x[PROP_CUR_CLIMATE_AREA_ID-(10037)]
	_ = x[PROP_CUR_CLIMATE_AREA_CLIMATE_TYPE-(10038)]
	_ = x[PROP_PLAYER_WORLD_LEVEL_LIMIT-(10039)]
	_ = x[PROP_PLAYER_WORLD_LEVEL_ADJUST_CD-(10040)]
	_ = x[PROP_PLAYER_LEGENDARY_DAILY_TASK_NUM-(10041)]
	_ = x[PROP_PLAYER_HOME_COIN-(10042)]
	_ = x[PROP_PLAYER_WAIT_SUB_HOME_COIN-(10043)]
	_ = x[PROP_IS_AUTO_UNLOCK_SPECIFIC_EQUIP-(10044)]
	_ = x[PROP_PLAYER_GCG_COIN-(10045)]
	_ = x[PROP_PLAYER_WAIT_SUB_GCG_COIN-(10046)]
	_ = x[PROP_PLAYER_ONLINE_TIME-(10047)]
	_ = x[PROP_IS_DIVEABLE-(10048)]
	_ = x[PROP_MAX_DIVE_STAMINA-(10049)]
	_ = x[PROP_CUR_PERSIST_DIVE_STAMINA-(10050)]
	_ = x[PROP_IS_CAN_PUT_FIVE_STAR_RELIQUARY-(10051)]
	_ = x[PROP_IS_AUTO_LOCK_FIVE_STAR_RELIQUARY-(10052)]
	_ = x[PROP_PLAYER_ROLE_COMBAT_COIN-(10053)]
	_ = x[PROP_CUR_PHLOGISTON-(10054)]
	_ = x[PROP_RELIQUARY_TEMPORARY_EXP-(10055)]
	_ = x[PROP_IS_MP_CROSS_PLATFORM_ENABLED-(10056)]
	_ = x[PROP_IS_ONLY_MP_WITH_PLATFORM_PLAYER-(10057)]
	_ = x[PROP_PLAYER_MUSIC_GAME_BOOK_COIN-(10058)]
	_ = x[PROP_IS_NOT_SHOW_RELIQUARY_RECOMMAND_PROP-(10059)]
	_ = x[PROP_SHOW_RELIQUARY_RECOMMAND_PROP_STATUS-(10100)]
}

var _PlayerPropValues = []PlayerProp{PROP_NONE, PROP_EXP, PROP_BREAK_LEVEL, PROP_SATIATION_VAL, PROP_SATIATION_PENALTY_TIME, PROP_GEAR_START_VAL, PROP_GEAR_STOP_VAL, PROP_LEVEL, PROP_LAST_CHANGE_AVATAR_TIME, PROP_MAX_SPRING_VOLUME, PROP_CUR_SPRING_VOLUME, PROP_IS_SPRING_AUTO_USE, PROP_SPRING_AUTO_USE_PERCENT, PROP_IS_FLYABLE, PROP_IS_WEATHER_LOCKED, PROP_IS_GAME_TIME_LOCKED, PROP_IS_TRANSFERABLE, PROP_MAX_STAMINA, PROP_CUR_PERSIST_STAMINA, PROP_CUR_TEMPORARY_STAMINA, PROP_PLAYER_LEVEL, PROP_PLAYER_EXP, PROP_PLAYER_HCOIN, PROP_PLAYER_SCOIN, PROP_PLAYER_MP_SETTING_TYPE, PROP_IS_MP_MODE_AVAILABLE, PROP_PLAYER_WORLD_LEVEL, PROP_PLAYER_RESIN, PROP_PLAYER_WAIT_SUB_HCOIN, PROP_PLAYER_WAIT_SUB_SCOIN, PROP_IS_ONLY_MP_WITH_PS_PLAYER, PROP_PLAYER_MCOIN, PROP_PLAYER_WAIT_SUB_MCOIN, PROP_PLAYER_LEGENDARY_KEY, PROP_IS_HAS_FIRST_SHARE, PROP_PLAYER_FORGE_POINT, PROP_CUR_CLIMATE_METER, PROP_CUR_CLIMATE_TYPE, PROP_CUR_CLIMATE_AREA_ID, PROP_CUR_CLIMATE_AREA_CLIMATE_TYPE, PROP_PLAYER_WORLD_LEVEL_LIMIT, PROP_PLAYER_WORLD_LEVEL_ADJUST_CD, PROP_PLAYER_LEGENDARY_DAILY_TASK_NUM, PROP_PLAYER_HOME_COIN, PROP_PLAYER_WAIT_SUB_HOME_COIN, PROP_IS_AUTO_UNLOCK_SPECIFIC_EQUIP, PROP_PLAYER_GCG_COIN, PROP_PLAYER_WAIT_SUB_GCG_COIN, PROP_PLAYER_ONLINE_TIME, PROP_IS_DIVEABLE, PROP_MAX_DIVE_STAMINA, PROP_CUR_PERSIST_DIVE_STAMINA, PROP_IS_CAN_PUT_FIVE_STAR_RELIQUARY, PROP_IS_AUTO_LOCK_FIVE_STAR_RELIQUARY, PROP_PLAYER_ROLE_COMBAT_COIN, PROP_CUR_PHLOGISTON, PROP_RELIQUARY_TEMPORARY_EXP, PROP_IS_MP_CROSS_PLATFORM_ENABLED, PROP_IS_ONLY_MP_WITH_PLATFORM_PLAYER, PROP_PLAYER_MUSIC_GAME_BOOK_COIN, PROP_IS_NOT_SHOW_RELIQUARY_RECOMMAND_PROP, PROP_SHOW_RELIQUARY_RECOMMAND_PROP_STATUS}

var _PlayerPropNameToValueMap = map[string]PlayerProp{
	_PlayerPropName_0[0:9]:          PROP_NONE,
	_PlayerPropLowerName_0[0:9]:     PROP_NONE,
	_PlayerPropName_1[0:8]:          PROP_EXP,
	_PlayerPropLowerName_1[0:8]:     PROP_EXP,
	_PlayerPropName_1[8:24]:         PROP_BREAK_LEVEL,
	_PlayerPropLowerName_1[8:24]:    PROP_BREAK_LEVEL,
	_PlayerPropName_1[24:42]:        PROP_SATIATION_VAL,
	_PlayerPropLowerName_1[24:42]:   PROP_SATIATION_VAL,
	_PlayerPropName_1[42:69]:        PROP_SATIATION_PENALTY_TIME,
	_PlayerPropLowerName_1[42:69]:   PROP_SATIATION_PENALTY_TIME,
	_PlayerPropName_2[0:19]:         PROP_GEAR_START_VAL,
	_PlayerPropLowerName_2[0:19]:    PROP_GEAR_START_VAL,
	_PlayerPropName_2[19:37]:        PROP_GEAR_STOP_VAL,
	_PlayerPropLowerName_2[19:37]:   PROP_GEAR_STOP_VAL,
	_PlayerPropName_3[0:10]:         PROP_LEVEL,
	_PlayerPropLowerName_3[0:10]:    PROP_LEVEL,
	_PlayerPropName_4[0:28]:         PROP_LAST_CHANGE_AVATAR_TIME,
	_PlayerPropLowerName_4[0:28]:    PROP_LAST_CHANGE_AVATAR_TIME,
	_PlayerPropName_4[28:50]:        PROP_MAX_SPRING_VOLUME,
	_PlayerPropLowerName_4[28:50]:   PROP_MAX_SPRING_VOLUME,
	_PlayerPropName_4[50:72]:        PROP_CUR_SPRING_VOLUME,
	_PlayerPropLowerName_4[50:72]:   PROP_CUR_SPRING_VOLUME,
	_PlayerPropName_4[72:95]:        PROP_IS_SPRING_AUTO_USE,
	_PlayerPropLowerName_4[72:95]:   PROP_IS_SPRING_AUTO_USE,
	_PlayerPropName_4[95:123]:       PROP_SPRING_AUTO_USE_PERCENT,
	_PlayerPropLowerName_4[95:123]:  PROP_SPRING_AUTO_USE_PERCENT,
	_PlayerPropName_4[123:138]:      PROP_IS_FLYABLE,
	_PlayerPropLowerName_4[123:138]: PROP_IS_FLYABLE,
	_PlayerPropName_4[138:160]:      PROP_IS_WEATHER_LOCKED,
	_PlayerPropLowerName_4[138:160]: PROP_IS_WEATHER_LOCKED,
	_PlayerPropName_4[160:184]:      PROP_IS_GAME_TIME_LOCKED,
	_PlayerPropLowerName_4[160:184]: PROP_IS_GAME_TIME_LOCKED,
	_PlayerPropName_4[184:204]:      PROP_IS_TRANSFERABLE,
	_PlayerPropLowerName_4[184:204]: PROP_IS_TRANSFERABLE,
	_PlayerPropName_4[204:220]:      PROP_MAX_STAMINA,
	_PlayerPropLowerName_4[204:220]: PROP_MAX_STAMINA,
	_PlayerPropName_4[220:244]:      PROP_CUR_PERSIST_STAMINA,
	_PlayerPropLowerName_4[220:244]: PROP_CUR_PERSIST_STAMINA,
	_PlayerPropName_4[244:270]:      PROP_CUR_TEMPORARY_STAMINA,
	_PlayerPropLowerName_4[244:270]: PROP_CUR_TEMPORARY_STAMINA,
	_PlayerPropName_4[270:287]:      PROP_PLAYER_LEVEL,
	_PlayerPropLowerName_4[270:287]: PROP_PLAYER_LEVEL,
	_PlayerPropName_4[287:302]:      PROP_PLAYER_EXP,
	_PlayerPropLowerName_4[287:302]: PROP_PLAYER_EXP,
	_PlayerPropName_4[302:319]:      PROP_PLAYER_HCOIN,
	_PlayerPropLowerName_4[302:319]: PROP_PLAYER_HCOIN,
	_PlayerPropName_4[319:336]:      PROP_PLAYER_SCOIN,
	_PlayerPropLowerName_4[319:336]: PROP_PLAYER_SCOIN,
	_PlayerPropName_4[336:363]:      PROP_PLAYER_MP_SETTING_TYPE,
	_PlayerPropLowerName_4[336:363]: PROP_PLAYER_MP_SETTING_TYPE,
	_PlayerPropName_4[363:388]:      PROP_IS_MP_MODE_AVAILABLE,
	_PlayerPropLowerName_4[363:388]: PROP_IS_MP_MODE_AVAILABLE,
	_PlayerPropName_4[388:411]:      PROP_PLAYER_WORLD_LEVEL,
	_PlayerPropLowerName_4[388:411]: PROP_PLAYER_WORLD_LEVEL,
	_PlayerPropName_4[411:428]:      PROP_PLAYER_RESIN,
	_PlayerPropLowerName_4[411:428]: PROP_PLAYER_RESIN,
	_PlayerPropName_5[0:26]:         PROP_PLAYER_WAIT_SUB_HCOIN,
	_PlayerPropLowerName_5[0:26]:    PROP_PLAYER_WAIT_SUB_HCOIN,
	_PlayerPropName_5[26:52]:        PROP_PLAYER_WAIT_SUB_SCOIN,
	_PlayerPropLowerName_5[26:52]:   PROP_PLAYER_WAIT_SUB_SCOIN,
	_PlayerPropName_5[52:82]:        PROP_IS_ONLY_MP_WITH_PS_PLAYER,
	_PlayerPropLowerName_5[52:82]:   PROP_IS_ONLY_MP_WITH_PS_PLAYER,
	_PlayerPropName_5[82:99]:        PROP_PLAYER_MCOIN,
	_PlayerPropLowerName_5[82:99]:   PROP_PLAYER_MCOIN,
	_PlayerPropName_5[99:125]:       PROP_PLAYER_WAIT_SUB_MCOIN,
	_PlayerPropLowerName_5[99:125]:  PROP_PLAYER_WAIT_SUB_MCOIN,
	_PlayerPropName_5[125:150]:      PROP_PLAYER_LEGENDARY_KEY,
	_PlayerPropLowerName_5[125:150]: PROP_PLAYER_LEGENDARY_KEY,
	_PlayerPropName_5[150:173]:      PROP_IS_HAS_FIRST_SHARE,
	_PlayerPropLowerName_5[150:173]: PROP_IS_HAS_FIRST_SHARE,
	_PlayerPropName_5[173:196]:      PROP_PLAYER_FORGE_POINT,
	_PlayerPropLowerName_5[173:196]: PROP_PLAYER_FORGE_POINT,
	_PlayerPropName_6[0:22]:         PROP_CUR_CLIMATE_METER,
	_PlayerPropLowerName_6[0:22]:    PROP_CUR_CLIMATE_METER,
	_PlayerPropName_6[22:43]:        PROP_CUR_CLIMATE_TYPE,
	_PlayerPropLowerName_6[22:43]:   PROP_CUR_CLIMATE_TYPE,
	_PlayerPropName_6[43:67]:        PROP_CUR_CLIMATE_AREA_ID,
	_PlayerPropLowerName_6[43:67]:   PROP_CUR_CLIMATE_AREA_ID,
	_PlayerPropName_6[67:101]:       PROP_CUR_CLIMATE_AREA_CLIMATE_TYPE,
	_PlayerPropLowerName_6[67:101]:  PROP_CUR_CLIMATE_AREA_CLIMATE_TYPE,
	_PlayerPropName_6[101:130]:      PROP_PLAYER_WORLD_LEVEL_LIMIT,
	_PlayerPropLowerName_6[101:130]: PROP_PLAYER_WORLD_LEVEL_LIMIT,
	_PlayerPropName_6[130:163]:      PROP_PLAYER_WORLD_LEVEL_ADJUST_CD,
	_PlayerPropLowerName_6[130:163]: PROP_PLAYER_WORLD_LEVEL_ADJUST_CD,
	_PlayerPropName_6[163:199]:      PROP_PLAYER_LEGENDARY_DAILY_TASK_NUM,
	_PlayerPropLowerName_6[163:199]: PROP_PLAYER_LEGENDARY_DAILY_TASK_NUM,
	_PlayerPropName_6[199:220]:      PROP_PLAYER_HOME_COIN,
	_PlayerPropLowerName_6[199:220]: PROP_PLAYER_HOME_COIN,
	_PlayerPropName_6[220:250]:      PROP_PLAYER_WAIT_SUB_HOME_COIN,
	_PlayerPropLowerName_6[220:250]: PROP_PLAYER_WAIT_SUB_HOME_COIN,
	_PlayerPropName_6[250:284]:      PROP_IS_AUTO_UNLOCK_SPECIFIC_EQUIP,
	_PlayerPropLowerName_6[250:284]: PROP_IS_AUTO_UNLOCK_SPECIFIC_EQUIP,
	_PlayerPropName_6[284:304]:      PROP_PLAYER_GCG_COIN,
	_PlayerPropLowerName_6[284:304]: PROP_PLAYER_GCG_COIN,
	_PlayerPropName_6[304:333]:      PROP_PLAYER_WAIT_SUB_GCG_COIN,
	_PlayerPropLowerName_6[304:333]: PROP_PLAYER_WAIT_SUB_GCG_COIN,
	_PlayerPropName_6[333:356]:      PROP_PLAYER_ONLINE_TIME,
	_PlayerPropLowerName_6[333:356]: PROP_PLAYER_ONLINE_TIME,
	_PlayerPropName_6[356:372]:      PROP_IS_DIVEABLE,
	_PlayerPropLowerName_6[356:372]: PROP_IS_DIVEABLE,
	_PlayerPropName_6[372:393]:      PROP_MAX_DIVE_STAMINA,
	_PlayerPropLowerName_6[372:393]: PROP_MAX_DIVE_STAMINA,
	_PlayerPropName_6[393:422]:      PROP_CUR_PERSIST_DIVE_STAMINA,
	_PlayerPropLowerName_6[393:422]: PROP_CUR_PERSIST_DIVE_STAMINA,
	_PlayerPropName_6[422:457]:      PROP_IS_CAN_PUT_FIVE_STAR_RELIQUARY,
	_PlayerPropLowerName_6[422:457]: PROP_IS_CAN_PUT_FIVE_STAR_RELIQUARY,
	_PlayerPropName_6[457:494]:      PROP_IS_AUTO_LOCK_FIVE_STAR_RELIQUARY,
	_PlayerPropLowerName_6[457:494]: PROP_IS_AUTO_LOCK_FIVE_STAR_RELIQUARY,
	_PlayerPropName_6[494:522]:      PROP_PLAYER_ROLE_COMBAT_COIN,
	_PlayerPropLowerName_6[494:522]: PROP_PLAYER_ROLE_COMBAT_COIN,
	_PlayerPropName_6[522:541]:      PROP_CUR_PHLOGISTON,
	_PlayerPropLowerName_6[522:541]: PROP_CUR_PHLOGISTON,
	_PlayerPropName_6[541:569]:      PROP_RELIQUARY_TEMPORARY_EXP,
	_PlayerPropLowerName_6[541:569]: PROP_RELIQUARY_TEMPORARY_EXP,
	_PlayerPropName_6[569:602]:      PROP_IS_MP_CROSS_PLATFORM_ENABLED,
	_PlayerPropLowerName_6[569:602]: PROP_IS_MP_CROSS_PLATFORM_ENABLED,
	_PlayerPropName_6[602:638]:      PROP_IS_ONLY_MP_WITH_PLATFORM_PLAYER,
	_PlayerPropLowerName_6[602:638]: PROP_IS_ONLY_MP_WITH_PLATFORM_PLAYER,
	_PlayerPropName_6[638:670]:      PROP_PLAYER_MUSIC_GAME_BOOK_COIN,
	_PlayerPropLowerName_6[638:670]: PROP_PLAYER_MUSIC_GAME_BOOK_COIN,
	_PlayerPropName_6[670:711]:      PROP_IS_NOT_SHOW_RELIQUARY_RECOMMAND_PROP,
	_PlayerPropLowerName_6[670:711]: PROP_IS_NOT_SHOW_RELIQUARY_RECOMMAND_PROP,
	_PlayerPropName_7[0:41]:         PROP_SHOW_RELIQUARY_RECOMMAND_PROP_STATUS,
	_PlayerPropLowerName_7[0:41]:    PROP_SHOW_RELIQUARY_RECOMMAND_PROP_STATUS,
}

var _PlayerPropNames = []string{
	_PlayerPropName_0[0:9],
	_PlayerPropName_1[0:8],
	_PlayerPropName_1[8:24],
	_PlayerPropName_1[24:42],
	_PlayerPropName_1[42:69],
	_PlayerPropName_2[0:19],
	_PlayerPropName_2[19:37],
	_PlayerPropName_3[0:10],
	_PlayerPropName_4[0:28],
	_PlayerPropName_4[28:50],
	_PlayerPropName_4[50:72],
	_PlayerPropName_4[72:95],
	_PlayerPropName_4[95:123],
	_PlayerPropName_4[123:138],
	_PlayerPropName_4[138:160],
	_PlayerPropName_4[160:184],
	_PlayerPropName_4[184:204],
	_PlayerPropName_4[204:220],
	_PlayerPropName_4[220:244],
	_PlayerPropName_4[244:270],
	_PlayerPropName_4[270:287],
	_PlayerPropName_4[287:302],
	_PlayerPropName_4[302:319],
	_PlayerPropName_4[319:336],
	_PlayerPropName_4[336:363],
	_PlayerPropName_4[363:388],
	_PlayerPropName_4[388:411],
	_PlayerPropName_4[411:428],
	_PlayerPropName_5[0:26],
	_PlayerPropName_5[26:52],
	_PlayerPropName_5[52:82],
	_PlayerPropName_5[82:99],
	_PlayerPropName_5[99:125],
	_PlayerPropName_5[125:150],
	_PlayerPropName_5[150:173],
	_PlayerPropName_5[173:196],
	_PlayerPropName_6[0:22],
	_PlayerPropName_6[22:43],
	_PlayerPropName_6[43:67],
	_PlayerPropName_6[67:101],
	_PlayerPropName_6[101:130],
	_PlayerPropName_6[130:163],
	_PlayerPropName_6[163:199],
	_PlayerPropName_6[199:220],
	_PlayerPropName_6[220:250],
	_PlayerPropName_6[250:284],
	_PlayerPropName_6[284:304],
	_PlayerPropName_6[304:333],
	_PlayerPropName_6[333:356],
	_PlayerPropName_6[356:372],
	_PlayerPropName_6[372:393],
	_PlayerPropName_6[393:422],
	_PlayerPropName_6[422:457],
	_PlayerPropName_6[457:494],
	_PlayerPropName_6[494:522],
	_PlayerPropName_6[522:541],
	_PlayerPropName_6[541:569],
	_PlayerPropName_6[569:602],
	_PlayerPropName_6[602:638],
	_PlayerPropName_6[638:670],
	_PlayerPropName_6[670:711],
	_PlayerPropName_7[0:41],
}

// PlayerPropString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PlayerPropString(s string) (PlayerProp, error) {
	if val, ok := _PlayerPropNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PlayerPropNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PlayerProp values", s)
}

// PlayerPropValues returns all values of the enum
func PlayerPropValues() []PlayerProp {
	return _PlayerPropValues
}

// PlayerPropStrings returns a slice of all String values of the enum
func PlayerPropStrings() []string {
	strs := make([]string, len(_PlayerPropNames))
	copy(strs, _PlayerPropNames)
	return strs
}

// IsAPlayerProp returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PlayerProp) IsAPlayerProp() bool {
	for _, v := range _PlayerPropValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PlayerProp
func (i PlayerProp) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PlayerProp
func (i *PlayerProp) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PlayerProp should be a string, got %s", data)
	}

	var err error
	*i, err = PlayerPropString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PlayerProp
func (i PlayerProp) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PlayerProp
func (i *PlayerProp) UnmarshalText(text []byte) error {
	var err error
	*i, err = PlayerPropString(string(text))
	return err
}
