// Code generated by "enumer --text --json --type=ReactionType -trimprefix=Reaction reactiontype.go"; DO NOT EDIT.

package excel

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_ReactionTypeName_0      = "NoneExplodeStreamBurningBurnedWetOvergrowMeltFreezeAntiFireRockSlowDownShockWindElectricFireSuperconductorSwirlFireSwirlWaterSwirlElectricSwirlIceSwirlFireAccuSwirlWaterAccuSwirlElectricAccuSwirlIceAccuStickRockStickWaterCrystallizeFireCrystallizeWaterCrystallizeElectricCrystallizeIceFrozenBrokenStickGrassOverdoseOverdoseElectricOverdoseGrassOvergrowMushroomFireOvergrowMushroomElectricPhlogistonSolidificationPhlogistonSolidificationEndMoonShockMoonOvergrowMoonCrystallizeWaterStarSuperconductor"
	_ReactionTypeLowerName_0 = "noneexplodestreamburningburnedwetovergrowmeltfreezeantifirerockslowdownshockwindelectricfiresuperconductorswirlfireswirlwaterswirlelectricswirliceswirlfireaccuswirlwateraccuswirlelectricaccuswirliceaccustickrockstickwatercrystallizefirecrystallizewatercrystallizeelectriccrystallizeicefrozenbrokenstickgrassoverdoseoverdoseelectricoverdosegrassovergrowmushroomfireovergrowmushroomelectricphlogistonsolidificationphlogistonsolidificationendmoonshockmoonovergrowmooncrystallizewaterstarsuperconductor"
	_ReactionTypeName_1      = "StarSwirlIce"
	_ReactionTypeLowerName_1 = "starswirlice"
)

var (
	_ReactionTypeIndex_0 = [...]uint16{0, 4, 11, 17, 24, 30, 33, 41, 45, 51, 59, 63, 71, 76, 80, 88, 92, 106, 115, 125, 138, 146, 159, 173, 190, 202, 211, 221, 236, 252, 271, 285, 297, 307, 315, 331, 344, 364, 388, 412, 439, 448, 460, 480, 498}
	_ReactionTypeIndex_1 = [...]uint8{0, 12}
)

func (i ReactionType) String() string {
	switch {
	case 0 <= i && i <= 43:
		return _ReactionTypeName_0[_ReactionTypeIndex_0[i]:_ReactionTypeIndex_0[i+1]]
	case i == 47:
		return _ReactionTypeName_1
	default:
		return fmt.Sprintf("ReactionType(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReactionTypeNoOp() {
	var x [1]struct{}
	_ = x[ReactionNone-(0)]
	_ = x[ReactionExplode-(1)]
	_ = x[ReactionStream-(2)]
	_ = x[ReactionBurning-(3)]
	_ = x[ReactionBurned-(4)]
	_ = x[ReactionWet-(5)]
	_ = x[ReactionOvergrow-(6)]
	_ = x[ReactionMelt-(7)]
	_ = x[ReactionFreeze-(8)]
	_ = x[ReactionAntiFire-(9)]
	_ = x[ReactionRock-(10)]
	_ = x[ReactionSlowDown-(11)]
	_ = x[ReactionShock-(12)]
	_ = x[ReactionWind-(13)]
	_ = x[ReactionElectric-(14)]
	_ = x[ReactionFire-(15)]
	_ = x[ReactionSuperconductor-(16)]
	_ = x[ReactionSwirlFire-(17)]
	_ = x[ReactionSwirlWater-(18)]
	_ = x[ReactionSwirlElectric-(19)]
	_ = x[ReactionSwirlIce-(20)]
	_ = x[ReactionSwirlFireAccu-(21)]
	_ = x[ReactionSwirlWaterAccu-(22)]
	_ = x[ReactionSwirlElectricAccu-(23)]
	_ = x[ReactionSwirlIceAccu-(24)]
	_ = x[ReactionStickRock-(25)]
	_ = x[ReactionStickWater-(26)]
	_ = x[ReactionCrystallizeFire-(27)]
	_ = x[ReactionCrystallizeWater-(28)]
	_ = x[ReactionCrystallizeElectric-(29)]
	_ = x[ReactionCrystallizeIce-(30)]
	_ = x[ReactionFrozenBroken-(31)]
	_ = x[ReactionStickGrass-(32)]
	_ = x[ReactionOverdose-(33)]
	_ = x[ReactionOverdoseElectric-(34)]
	_ = x[ReactionOverdoseGrass-(35)]
	_ = x[ReactionOvergrowMushroomFire-(36)]
	_ = x[ReactionOvergrowMushroomElectric-(37)]
	_ = x[ReactionPhlogistonSolidification-(38)]
	_ = x[ReactionPhlogistonSolidificationEnd-(39)]
	_ = x[ReactionMoonShock-(40)]
	_ = x[ReactionMoonOvergrow-(41)]
	_ = x[ReactionMoonCrystallizeWater-(42)]
	_ = x[ReactionStarSuperconductor-(43)]
	_ = x[ReactionStarSwirlIce-(47)]
}

var _ReactionTypeValues = []ReactionType{ReactionNone, ReactionExplode, ReactionStream, ReactionBurning, ReactionBurned, ReactionWet, ReactionOvergrow, ReactionMelt, ReactionFreeze, ReactionAntiFire, ReactionRock, ReactionSlowDown, ReactionShock, ReactionWind, ReactionElectric, ReactionFire, ReactionSuperconductor, ReactionSwirlFire, ReactionSwirlWater, ReactionSwirlElectric, ReactionSwirlIce, ReactionSwirlFireAccu, ReactionSwirlWaterAccu, ReactionSwirlElectricAccu, ReactionSwirlIceAccu, ReactionStickRock, ReactionStickWater, ReactionCrystallizeFire, ReactionCrystallizeWater, ReactionCrystallizeElectric, ReactionCrystallizeIce, ReactionFrozenBroken, ReactionStickGrass, ReactionOverdose, ReactionOverdoseElectric, ReactionOverdoseGrass, ReactionOvergrowMushroomFire, ReactionOvergrowMushroomElectric, ReactionPhlogistonSolidification, ReactionPhlogistonSolidificationEnd, ReactionMoonShock, ReactionMoonOvergrow, ReactionMoonCrystallizeWater, ReactionStarSuperconductor, ReactionStarSwirlIce}

var _ReactionTypeNameToValueMap = map[string]ReactionType{
	_ReactionTypeName_0[0:4]:          ReactionNone,
	_ReactionTypeLowerName_0[0:4]:     ReactionNone,
	_ReactionTypeName_0[4:11]:         ReactionExplode,
	_ReactionTypeLowerName_0[4:11]:    ReactionExplode,
	_ReactionTypeName_0[11:17]:        ReactionStream,
	_ReactionTypeLowerName_0[11:17]:   ReactionStream,
	_ReactionTypeName_0[17:24]:        ReactionBurning,
	_ReactionTypeLowerName_0[17:24]:   ReactionBurning,
	_ReactionTypeName_0[24:30]:        ReactionBurned,
	_ReactionTypeLowerName_0[24:30]:   ReactionBurned,
	_ReactionTypeName_0[30:33]:        ReactionWet,
	_ReactionTypeLowerName_0[30:33]:   ReactionWet,
	_ReactionTypeName_0[33:41]:        ReactionOvergrow,
	_ReactionTypeLowerName_0[33:41]:   ReactionOvergrow,
	_ReactionTypeName_0[41:45]:        ReactionMelt,
	_ReactionTypeLowerName_0[41:45]:   ReactionMelt,
	_ReactionTypeName_0[45:51]:        ReactionFreeze,
	_ReactionTypeLowerName_0[45:51]:   ReactionFreeze,
	_ReactionTypeName_0[51:59]:        ReactionAntiFire,
	_ReactionTypeLowerName_0[51:59]:   ReactionAntiFire,
	_ReactionTypeName_0[59:63]:        ReactionRock,
	_ReactionTypeLowerName_0[59:63]:   ReactionRock,
	_ReactionTypeName_0[63:71]:        ReactionSlowDown,
	_ReactionTypeLowerName_0[63:71]:   ReactionSlowDown,
	_ReactionTypeName_0[71:76]:        ReactionShock,
	_ReactionTypeLowerName_0[71:76]:   ReactionShock,
	_ReactionTypeName_0[76:80]:        ReactionWind,
	_ReactionTypeLowerName_0[76:80]:   ReactionWind,
	_ReactionTypeName_0[80:88]:        ReactionElectric,
	_ReactionTypeLowerName_0[80:88]:   ReactionElectric,
	_ReactionTypeName_0[88:92]:        ReactionFire,
	_ReactionTypeLowerName_0[88:92]:   ReactionFire,
	_ReactionTypeName_0[92:106]:       ReactionSuperconductor,
	_ReactionTypeLowerName_0[92:106]:  ReactionSuperconductor,
	_ReactionTypeName_0[106:115]:      ReactionSwirlFire,
	_ReactionTypeLowerName_0[106:115]: ReactionSwirlFire,
	_ReactionTypeName_0[115:125]:      ReactionSwirlWater,
	_ReactionTypeLowerName_0[115:125]: ReactionSwirlWater,
	_ReactionTypeName_0[125:138]:      ReactionSwirlElectric,
	_ReactionTypeLowerName_0[125:138]: ReactionSwirlElectric,
	_ReactionTypeName_0[138:146]:      ReactionSwirlIce,
	_ReactionTypeLowerName_0[138:146]: ReactionSwirlIce,
	_ReactionTypeName_0[146:159]:      ReactionSwirlFireAccu,
	_ReactionTypeLowerName_0[146:159]: ReactionSwirlFireAccu,
	_ReactionTypeName_0[159:173]:      ReactionSwirlWaterAccu,
	_ReactionTypeLowerName_0[159:173]: ReactionSwirlWaterAccu,
	_ReactionTypeName_0[173:190]:      ReactionSwirlElectricAccu,
	_ReactionTypeLowerName_0[173:190]: ReactionSwirlElectricAccu,
	_ReactionTypeName_0[190:202]:      ReactionSwirlIceAccu,
	_ReactionTypeLowerName_0[190:202]: ReactionSwirlIceAccu,
	_ReactionTypeName_0[202:211]:      ReactionStickRock,
	_ReactionTypeLowerName_0[202:211]: ReactionStickRock,
	_ReactionTypeName_0[211:221]:      ReactionStickWater,
	_ReactionTypeLowerName_0[211:221]: ReactionStickWater,
	_ReactionTypeName_0[221:236]:      ReactionCrystallizeFire,
	_ReactionTypeLowerName_0[221:236]: ReactionCrystallizeFire,
	_ReactionTypeName_0[236:252]:      ReactionCrystallizeWater,
	_ReactionTypeLowerName_0[236:252]: ReactionCrystallizeWater,
	_ReactionTypeName_0[252:271]:      ReactionCrystallizeElectric,
	_ReactionTypeLowerName_0[252:271]: ReactionCrystallizeElectric,
	_ReactionTypeName_0[271:285]:      ReactionCrystallizeIce,
	_ReactionTypeLowerName_0[271:285]: ReactionCrystallizeIce,
	_ReactionTypeName_0[285:297]:      ReactionFrozenBroken,
	_ReactionTypeLowerName_0[285:297]: ReactionFrozenBroken,
	_ReactionTypeName_0[297:307]:      ReactionStickGrass,
	_ReactionTypeLowerName_0[297:307]: ReactionStickGrass,
	_ReactionTypeName_0[307:315]:      ReactionOverdose,
	_ReactionTypeLowerName_0[307:315]: ReactionOverdose,
	_ReactionTypeName_0[315:331]:      ReactionOverdoseElectric,
	_ReactionTypeLowerName_0[315:331]: ReactionOverdoseElectric,
	_ReactionTypeName_0[331:344]:      ReactionOverdoseGrass,
	_ReactionTypeLowerName_0[331:344]: ReactionOverdoseGrass,
	_ReactionTypeName_0[344:364]:      ReactionOvergrowMushroomFire,
	_ReactionTypeLowerName_0[344:364]: ReactionOvergrowMushroomFire,
	_ReactionTypeName_0[364:388]:      ReactionOvergrowMushroomElectric,
	_ReactionTypeLowerName_0[364:388]: ReactionOvergrowMushroomElectric,
	_ReactionTypeName_0[388:412]:      ReactionPhlogistonSolidification,
	_ReactionTypeLowerName_0[388:412]: ReactionPhlogistonSolidification,
	_ReactionTypeName_0[412:439]:      ReactionPhlogistonSolidificationEnd,
	_ReactionTypeLowerName_0[412:439]: ReactionPhlogistonSolidificationEnd,
	_ReactionTypeName_0[439:448]:      ReactionMoonShock,
	_ReactionTypeLowerName_0[439:448]: ReactionMoonShock,
	_ReactionTypeName_0[448:460]:      ReactionMoonOvergrow,
	_ReactionTypeLowerName_0[448:460]: ReactionMoonOvergrow,
	_ReactionTypeName_0[460:480]:      ReactionMoonCrystallizeWater,
	_ReactionTypeLowerName_0[460:480]: ReactionMoonCrystallizeWater,
	_ReactionTypeName_0[480:498]:      ReactionStarSuperconductor,
	_ReactionTypeLowerName_0[480:498]: ReactionStarSuperconductor,
	_ReactionTypeName_1[0:12]:         ReactionStarSwirlIce,
	_ReactionTypeLowerName_1[0:12]:    ReactionStarSwirlIce,
}

var _ReactionTypeNames = []string{
	_ReactionTypeName_0[0:4],
	_ReactionTypeName_0[4:11],
	_ReactionTypeName_0[11:17],
	_ReactionTypeName_0[17:24],
	_ReactionTypeName_0[24:30],
	_ReactionTypeName_0[30:33],
	_ReactionTypeName_0[33:41],
	_ReactionTypeName_0[41:45],
	_ReactionTypeName_0[45:51],
	_ReactionTypeName_0[51:59],
	_ReactionTypeName_0[59:63],
	_ReactionTypeName_0[63:71],
	_ReactionTypeName_0[71:76],
	_ReactionTypeName_0[76:80],
	_ReactionTypeName_0[80:88],
	_ReactionTypeName_0[88:92],
	_ReactionTypeName_0[92:106],
	_ReactionTypeName_0[106:115],
	_ReactionTypeName_0[115:125],
	_ReactionTypeName_0[125:138],
	_ReactionTypeName_0[138:146],
	_ReactionTypeName_0[146:159],
	_ReactionTypeName_0[159:173],
	_ReactionTypeName_0[173:190],
	_ReactionTypeName_0[190:202],
	_ReactionTypeName_0[202:211],
	_ReactionTypeName_0[211:221],
	_ReactionTypeName_0[221:236],
	_ReactionTypeName_0[236:252],
	_ReactionTypeName_0[252:271],
	_ReactionTypeName_0[271:285],
	_ReactionTypeName_0[285:297],
	_ReactionTypeName_0[297:307],
	_ReactionTypeName_0[307:315],
	_ReactionTypeName_0[315:331],
	_ReactionTypeName_0[331:344],
	_ReactionTypeName_0[344:364],
	_ReactionTypeName_0[364:388],
	_ReactionTypeName_0[388:412],
	_ReactionTypeName_0[412:439],
	_ReactionTypeName_0[439:448],
	_ReactionTypeName_0[448:460],
	_ReactionTypeName_0[460:480],
	_ReactionTypeName_0[480:498],
	_ReactionTypeName_1[0:12],
}

// ReactionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReactionTypeString(s string) (ReactionType, error) {
	if val, ok := _ReactionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReactionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReactionType values", s)
}

// ReactionTypeValues returns all values of the enum
func ReactionTypeValues() []ReactionType {
	return _ReactionTypeValues
}

// ReactionTypeStrings returns a slice of all String values of the enum
func ReactionTypeStrings() []string {
	strs := make([]string, len(_ReactionTypeNames))
	copy(strs, _ReactionTypeNames)
	return strs
}

// IsAReactionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReactionType) IsAReactionType() bool {
	for _, v := range _ReactionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ReactionType
func (i ReactionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReactionType
func (i *ReactionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ReactionType should be a string, got %s", data)
	}

	var err error
	*i, err = ReactionTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ReactionType
func (i ReactionType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ReactionType
func (i *ReactionType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ReactionTypeString(string(text))
	return err
}
