package excel

//go:generate enumer --text --json --type=WeaponType $GOFILE
type WeaponType uint32

const (
	WEAPON_NONE WeaponType = iota
	WEAPON_SWORD_ONE_HAND
	WEAPON_CROSSBOW
	WEAPON_STAFF
	WEAPON_DOUBLE_DAGGER
	WEAPON_KATANA
	WEAPON_SHURIKEN
	WEAPON_STICK
	WEAPON_SPEAR
	WEAPON_SHIELD_SMALL
	WEAPON_CATALYST
	WEAPON_CLAYMORE
	WEAPON_BOW
	WEAPON_POLE
)
