// Code generated by "enumer --text --json --type=WeaponType weapontype.go"; DO NOT EDIT.

package excel

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _WeaponTypeName = "WEAPON_NONEWEAPON_SWORD_ONE_HANDWEAPON_CROSSBOWWEAPON_STAFFWEAPON_DOUBLE_DAGGERWEAPON_KATANAWEAPON_SHURIKENWEAPON_STICKWEAPON_SPEARWEAPON_SHIELD_SMALLWEAPON_CATALYSTWEAPON_CLAYMOREWEAPON_BOWWEAPON_POLE"

var _WeaponTypeIndex = [...]uint8{0, 11, 32, 47, 59, 79, 92, 107, 119, 131, 150, 165, 180, 190, 201}

const _WeaponTypeLowerName = "weapon_noneweapon_sword_one_handweapon_crossbowweapon_staffweapon_double_daggerweapon_katanaweapon_shurikenweapon_stickweapon_spearweapon_shield_smallweapon_catalystweapon_claymoreweapon_bowweapon_pole"

func (i WeaponType) String() string {
	if i >= WeaponType(len(_WeaponTypeIndex)-1) {
		return fmt.Sprintf("WeaponType(%d)", i)
	}
	return _WeaponTypeName[_WeaponTypeIndex[i]:_WeaponTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _WeaponTypeNoOp() {
	var x [1]struct{}
	_ = x[WEAPON_NONE-(0)]
	_ = x[WEAPON_SWORD_ONE_HAND-(1)]
	_ = x[WEAPON_CROSSBOW-(2)]
	_ = x[WEAPON_STAFF-(3)]
	_ = x[WEAPON_DOUBLE_DAGGER-(4)]
	_ = x[WEAPON_KATANA-(5)]
	_ = x[WEAPON_SHURIKEN-(6)]
	_ = x[WEAPON_STICK-(7)]
	_ = x[WEAPON_SPEAR-(8)]
	_ = x[WEAPON_SHIELD_SMALL-(9)]
	_ = x[WEAPON_CATALYST-(10)]
	_ = x[WEAPON_CLAYMORE-(11)]
	_ = x[WEAPON_BOW-(12)]
	_ = x[WEAPON_POLE-(13)]
}

var _WeaponTypeValues = []WeaponType{WEAPON_NONE, WEAPON_SWORD_ONE_HAND, WEAPON_CROSSBOW, WEAPON_STAFF, WEAPON_DOUBLE_DAGGER, WEAPON_KATANA, WEAPON_SHURIKEN, WEAPON_STICK, WEAPON_SPEAR, WEAPON_SHIELD_SMALL, WEAPON_CATALYST, WEAPON_CLAYMORE, WEAPON_BOW, WEAPON_POLE}

var _WeaponTypeNameToValueMap = map[string]WeaponType{
	_WeaponTypeName[0:11]:         WEAPON_NONE,
	_WeaponTypeLowerName[0:11]:    WEAPON_NONE,
	_WeaponTypeName[11:32]:        WEAPON_SWORD_ONE_HAND,
	_WeaponTypeLowerName[11:32]:   WEAPON_SWORD_ONE_HAND,
	_WeaponTypeName[32:47]:        WEAPON_CROSSBOW,
	_WeaponTypeLowerName[32:47]:   WEAPON_CROSSBOW,
	_WeaponTypeName[47:59]:        WEAPON_STAFF,
	_WeaponTypeLowerName[47:59]:   WEAPON_STAFF,
	_WeaponTypeName[59:79]:        WEAPON_DOUBLE_DAGGER,
	_WeaponTypeLowerName[59:79]:   WEAPON_DOUBLE_DAGGER,
	_WeaponTypeName[79:92]:        WEAPON_KATANA,
	_WeaponTypeLowerName[79:92]:   WEAPON_KATANA,
	_WeaponTypeName[92:107]:       WEAPON_SHURIKEN,
	_WeaponTypeLowerName[92:107]:  WEAPON_SHURIKEN,
	_WeaponTypeName[107:119]:      WEAPON_STICK,
	_WeaponTypeLowerName[107:119]: WEAPON_STICK,
	_WeaponTypeName[119:131]:      WEAPON_SPEAR,
	_WeaponTypeLowerName[119:131]: WEAPON_SPEAR,
	_WeaponTypeName[131:150]:      WEAPON_SHIELD_SMALL,
	_WeaponTypeLowerName[131:150]: WEAPON_SHIELD_SMALL,
	_WeaponTypeName[150:165]:      WEAPON_CATALYST,
	_WeaponTypeLowerName[150:165]: WEAPON_CATALYST,
	_WeaponTypeName[165:180]:      WEAPON_CLAYMORE,
	_WeaponTypeLowerName[165:180]: WEAPON_CLAYMORE,
	_WeaponTypeName[180:190]:      WEAPON_BOW,
	_WeaponTypeLowerName[180:190]: WEAPON_BOW,
	_WeaponTypeName[190:201]:      WEAPON_POLE,
	_WeaponTypeLowerName[190:201]: WEAPON_POLE,
}

var _WeaponTypeNames = []string{
	_WeaponTypeName[0:11],
	_WeaponTypeName[11:32],
	_WeaponTypeName[32:47],
	_WeaponTypeName[47:59],
	_WeaponTypeName[59:79],
	_WeaponTypeName[79:92],
	_WeaponTypeName[92:107],
	_WeaponTypeName[107:119],
	_WeaponTypeName[119:131],
	_WeaponTypeName[131:150],
	_WeaponTypeName[150:165],
	_WeaponTypeName[165:180],
	_WeaponTypeName[180:190],
	_WeaponTypeName[190:201],
}

// WeaponTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func WeaponTypeString(s string) (WeaponType, error) {
	if val, ok := _WeaponTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _WeaponTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to WeaponType values", s)
}

// WeaponTypeValues returns all values of the enum
func WeaponTypeValues() []WeaponType {
	return _WeaponTypeValues
}

// WeaponTypeStrings returns a slice of all String values of the enum
func WeaponTypeStrings() []string {
	strs := make([]string, len(_WeaponTypeNames))
	copy(strs, _WeaponTypeNames)
	return strs
}

// IsAWeaponType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i WeaponType) IsAWeaponType() bool {
	for _, v := range _WeaponTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for WeaponType
func (i WeaponType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for WeaponType
func (i *WeaponType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("WeaponType should be a string, got %s", data)
	}

	var err error
	*i, err = WeaponTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for WeaponType
func (i WeaponType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for WeaponType
func (i *WeaponType) UnmarshalText(text []byte) error {
	var err error
	*i, err = WeaponTypeString(string(text))
	return err
}
